# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.

[prune]
  go-tests = true
  non-go = true

# Require `revel` command (compiled later from vendor dir)
required = ["github.com/revel/cmd/revel"]
[[constraint]]
  name = "github.com/revel/cmd"
  version = "^0.19.0"

# Override version for transitive dependencies
# otherwise we fetch the latest.
[[override]]
  name = "github.com/revel/config"
  version = "^0.14.0"
[[override]]
  name = "github.com/revel/modules"
  version = "^0.14.0"
[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "github.com/fsnotify/fsnotify"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "^0.8.0"

[[constraint]]
  name = "github.com/revel/revel"
  version = "^0.14.0"

[[constraint]]
  name = "github.com/youtube/vitess"
  revision = "98f9189aa016e2a3afafa9ff42cde55bde421d3c"

[[constraint]]
  name = "github.com/percona/go-mysql"
  revision = "63da60b59ae83a05a8d447a5fdf2186ff3c37f4b"
